export { HomePage } from './home/home-page';
export { InicioPage } from './inicio/inicio-page';
export { RegistroPage } from './registro/registro-page';
export { LoginPage } from './login/login-page';
export { SobrePage } from './sobre/sobre-page';
export { PontosApoioPage } from './pontos-apoio/pontos-apoio-page';
export { DenunciaPage } from './denuncia/denuncia-page';
export { ConfirmacaoDenuncia } from './denuncia/confirmacao-denuncia';
export { DocumentosNorteadoresPage } from './documentos-norteadores/documentos-norteadores-page';
