name: Publish Docker image

on:
  push:
    branches: ['main']
  workflow_dispatch:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Opcional: instalar dependências do seu projeto, se necessário
      # - run: npm install
      # - run: GITHUB_TOKEN=${{ secrets.GH_TOKEN }} npm run release

      # Criar a imagem e enviar para o Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            huandrey/odonto-guardiao:latest
          build-args: |
            VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }}
